services:

  postgres:
    image: postgres:latest
    container_name: postgres-school-management
    environment:
      POSTGRES_USER: ffreitas
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: school_management_database
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - school-management-network
    restart: unless-stopped

  mail-dev:
    image: maildev/maildev
    container_name: mail-school-management
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - school-management-network
    restart: unless-stopped

  spring-application:
    image: school-management-system-spring:1.0.0
    container_name: spring-school-management
    environment:
      PROFILE: docker
      POSTGRES_DB: school_management_database
      POSTGRES_USER: ffreitas
      POSTGRES_PASSWORD: password
      JWT_SECRET: 1ziBfO3ls0+XFugZPnPLiLbTWoGDxB8e3W1kKISsJZPfIvstCGVqJEV67f0hqWGtjqvIwuQAEQD23/Pzt5p0/A==
      ADMIN_PASSWORD: adminschooldev
      MAIL_DEV_USERNAME: ffreitas
      MAIL_DEV_PASSWORD: 29101997
    ports:
      - "8080:8080"
    networks:
      - school-management-network
    volumes:
      - spring-application:/var/lib/spring-application/data
    depends_on:
      - postgres
      - mail-dev
    restart: unless-stopped

volumes:
  postgres:
    driver: local
  spring-application:
    driver: local

networks:
  school-management-network:
    driver: bridge